# Generated by Django 4.1.5 on 2023-01-26 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_order_posle_remont'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_do',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='time_posle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='person_pic',
            field=models.ImageField(default='images/def.jpg', upload_to='images/users/'),
        ),
    ]
